[tool.poetry]
name = "Snake"
version = "0.1.0"
description = ""
authors = ["Eugenio Ribeiro <eugeniodias5@hotmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"
pygame = "^1.9.6"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
